[package]
name = "chromasync"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Dynamic color engine and theme generator CLI"
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords = ["theme", "color", "cli", "palette", "desktop"]
categories = ["command-line-utilities", "config"]

[lib]
name = "chromasync_cli"
path = "src/lib.rs"

[[bin]]
name = "chromasync"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
chromasync-core = { version = "0.5.0", path = "../chromasync-core" }
chromasync-types = { version = "0.5.0", path = "../chromasync-types" }
clap.workspace = true
clap_complete = { workspace = true }
serde.workspace = true
serde_json.workspace = true
toml.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
predicates.workspace = true
