use std::{
    fmt::Write,
    fs,
    path::{Path, PathBuf},
};

use anyhow::{Context, Result, bail};
use chromasync_renderers::built_in_targets;
use chromasync_template::built_in_templates;
use clap::{CommandFactory, Parser, Subcommand};

const GENERATED_NOTICE: &str =
    "<!-- This file is auto-generated by `cargo run -p chromasync-docs -- generate`. -->";

#[derive(Debug, Parser)]
#[command(
    name = "chromasync-docs",
    about = "Generate mdBook content for Chromasync"
)]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Debug, Subcommand)]
enum Command {
    /// Generate the mdBook source files under book/src.
    Generate {
        /// Fail if generated files differ from what is checked in.
        #[arg(long)]
        check: bool,
    },
}

fn main() -> Result<()> {
    let cli = Cli::parse();

    match cli.command {
        Command::Generate { check } => generate_book(check),
    }
}

fn generate_book(check: bool) -> Result<()> {
    let root = workspace_root()?;
    let book_src = root.join("book").join("src");
    let outputs = [
        ("SUMMARY.md", render_summary()),
        ("index.md", render_index(&root)?),
        ("generated/cli.md", render_cli_reference()),
        ("generated/templates.md", render_templates_reference()?),
        ("generated/targets.md", render_targets_reference()),
        (
            "reference/product.md",
            render_reference_doc(&root, "docs/PRODUCT.md")?,
        ),
        (
            "reference/packaging.md",
            render_reference_doc(&root, "docs/PACKAGING.md")?,
        ),
    ];

    for (relative_path, content) in outputs {
        write_generated_file(&book_src.join(relative_path), &content, check)?;
    }

    // Ensure static feature guide stubs exist (never overwritten once created).
    let feature_guides = [
        ("guides/generate.md", "Generate"),
        ("guides/wallpaper.md", "Wallpaper"),
        ("guides/batch.md", "Batch"),
        ("guides/templates.md", "Templates"),
        ("guides/packs.md", "Packs"),
        ("guides/targets.md", "Targets"),
        ("guides/preview.md", "Preview"),
        ("guides/tokens.md", "Tokens"),
    ];

    for (relative_path, title) in feature_guides {
        let path = book_src.join(relative_path);
        if !path.exists() && !check {
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent)
                    .with_context(|| format!("failed to create '{}'", parent.display()))?;
            }
            fs::write(&path, format!("# {title}\n"))
                .with_context(|| format!("failed to write '{}'", path.display()))?;
        }
    }

    Ok(())
}

fn render_summary() -> String {
    format!(
        "{notice}\n\n# Summary\n\n\
         - [Introduction](index.md)\n\
         \n\
         # Guides\n\
         \n\
         - [Generate](guides/generate.md)\n\
         - [Wallpaper](guides/wallpaper.md)\n\
         - [Batch](guides/batch.md)\n\
         - [Templates](guides/templates.md)\n\
         - [Packs](guides/packs.md)\n\
         - [Targets](guides/targets.md)\n\
         - [Preview](guides/preview.md)\n\
         - [Tokens](guides/tokens.md)\n\
         \n\
         # Reference\n\
         \n\
         - [CLI Reference](generated/cli.md)\n\
         - [Built-in Templates](generated/templates.md)\n\
         - [Built-in Targets](generated/targets.md)\n\
         - [Product](reference/product.md)\n\
         - [Packaging](reference/packaging.md)\n",
        notice = GENERATED_NOTICE,
    )
}

fn render_index(root: &Path) -> Result<String> {
    let readme_path = root.join("README.md");
    let readme = fs::read_to_string(&readme_path)
        .with_context(|| format!("failed to read '{}'", readme_path.display()))?;
    let content = rewrite_markdown_links(&readme, root);

    Ok(format!("{GENERATED_NOTICE}\n\n{content}"))
}

fn render_cli_reference() -> String {
    let command = chromasync_cli::Cli::command();
    let mut output = String::new();

    let _ = writeln!(output, "{GENERATED_NOTICE}");
    let _ = writeln!(output);
    let _ = writeln!(output, "# CLI Reference");
    let _ = writeln!(output);
    let _ = writeln!(
        output,
        "This page is generated from the Clap command tree in `chromasync-cli`."
    );
    let _ = writeln!(output);

    render_command_section(&command, &["chromasync"], 2, &mut output);

    output
}

fn render_command_section(
    command: &clap::Command,
    path: &[&str],
    heading_level: usize,
    output: &mut String,
) {
    let heading = "#".repeat(heading_level);
    let full_name = path.join(" ");
    let mut rendered = command.clone();
    let help = rendered.render_long_help().to_string();

    let _ = writeln!(output, "{heading} `{full_name}`");
    let _ = writeln!(output);
    let _ = writeln!(output, "```text");
    let _ = write!(output, "{}", help.trim_end());
    let _ = writeln!(output);
    let _ = writeln!(output, "```");
    let _ = writeln!(output);

    let subcommands = command
        .get_subcommands()
        .filter(|subcommand| subcommand.get_name() != "help")
        .cloned()
        .collect::<Vec<_>>();

    for subcommand in subcommands {
        let mut next_path = path.to_vec();
        next_path.push(subcommand.get_name());
        render_command_section(&subcommand, &next_path, heading_level + 1, output);
    }
}

fn render_templates_reference() -> Result<String> {
    let mut templates = built_in_templates()?;
    templates.sort_by(|left, right| {
        left.definition.name.cmp(&right.definition.name).then(
            left.definition
                .mode
                .as_str()
                .cmp(right.definition.mode.as_str()),
        )
    });

    let mut output = String::new();
    let _ = writeln!(output, "{GENERATED_NOTICE}");
    let _ = writeln!(output);
    let _ = writeln!(output, "# Built-in Templates");
    let _ = writeln!(output);
    let _ = writeln!(
        output,
        "| Name | Mode | Description | Source |\n| --- | --- | --- | --- |"
    );

    for template in templates {
        let description = template
            .definition
            .description
            .unwrap_or_else(|| "-".to_owned());
        let _ = writeln!(
            output,
            "| `{}` | `{}` | {} | `{}` |",
            template.definition.name,
            template.definition.mode,
            escape_table_cell(&description),
            template.source.location(),
        );
    }

    Ok(output)
}

fn render_targets_reference() -> String {
    let mut output = String::new();
    let _ = writeln!(output, "{GENERATED_NOTICE}");
    let _ = writeln!(output);
    let _ = writeln!(output, "# Built-in Targets");
    let _ = writeln!(output);
    let _ = writeln!(output, "| Name | Default Artifact |\n| --- | --- |");

    for target in built_in_targets() {
        let _ = writeln!(
            output,
            "| `{}` | `{}` |",
            target.as_str(),
            target.file_name(),
        );
    }

    output
}

fn render_reference_doc(root: &Path, relative_path: &str) -> Result<String> {
    let path = root.join(relative_path);
    let content = fs::read_to_string(&path)
        .with_context(|| format!("failed to read '{}'", path.display()))?;
    let rewritten = rewrite_markdown_links(&content, root);

    Ok(format!("{GENERATED_NOTICE}\n\n{rewritten}"))
}

fn rewrite_markdown_links(content: &str, root: &Path) -> String {
    let mut output = String::with_capacity(content.len());
    let mut index = 0;
    let root_prefix = format!("{}/", root.display());

    while index < content.len() {
        let Some(relative_start) = content[index..].find('[') else {
            output.push_str(&content[index..]);
            break;
        };
        let start = index + relative_start;
        output.push_str(&content[index..start]);

        let Some(label_end_offset) = content[start + 1..].find(']') else {
            output.push_str(&content[start..]);
            break;
        };
        let label_end = start + 1 + label_end_offset;

        if !content[label_end + 1..].starts_with('(') {
            output.push_str(&content[start..=label_end]);
            index = label_end + 1;
            continue;
        }

        let Some(target_end_offset) = content[label_end + 2..].find(')') else {
            output.push_str(&content[start..]);
            break;
        };
        let target_end = label_end + 2 + target_end_offset;
        let label = &content[start + 1..label_end];
        let target = &content[label_end + 2..target_end];

        if let Some(rewritten) = rewrite_link(label, target, &root_prefix) {
            output.push_str(&rewritten);
        } else {
            output.push_str(&content[start..=target_end]);
        }

        index = target_end + 1;
    }

    output
}

fn rewrite_link(label: &str, target: &str, root_prefix: &str) -> Option<String> {
    let target = match target {
        "./docs/PACKAGING.md" => "reference/packaging.md",
        "./docs/PRODUCT.md" => "reference/product.md",
        "./PACKAGING.md" => "packaging.md",
        "./PRODUCT.md" => "product.md",
        _ => target,
    };

    if target.starts_with(root_prefix) {
        return Some(label.to_owned());
    }

    if target != label {
        return Some(format!("[{label}]({target})"));
    }

    None
}

fn write_generated_file(path: &Path, expected: &str, check: bool) -> Result<()> {
    if check {
        let actual = fs::read_to_string(path).with_context(|| {
            format!(
                "generated file '{}' is missing; run `cargo run -p chromasync-docs -- generate`",
                path.display()
            )
        })?;

        if actual != expected {
            bail!(
                "generated file '{}' is out of date; run `cargo run -p chromasync-docs -- generate`",
                path.display()
            );
        }

        return Ok(());
    }

    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("failed to create '{}'", parent.display()))?;
    }

    fs::write(path, expected).with_context(|| format!("failed to write '{}'", path.display()))
}

fn workspace_root() -> Result<PathBuf> {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .map(Path::to_path_buf)
        .context("failed to determine workspace root for docs generation")
}

fn escape_table_cell(value: &str) -> String {
    value.replace('\n', " ").replace('|', "\\|")
}
